apiVersion: "purelb.io/v1"
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
 local:
    v4pools:
    - aggregation: default
      pool: 192.168.1.230-192.168.1.240
      subnet: 192.168.1.0/24
