apiVersion: "purelb.io/v1"
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
 local:
    v4pools:
    - aggregation: default
      pool: 192.168.0.51-192.168.0.60
      subnet: 192.168.0.0/24
